@ECHO OFF
SET SUBLIME=Sublime Text 3

:COPYFILES
:: Check if folder exist
IF NOT EXIST "%SUBLIME%-data\" GOTO :END
ROBOCOPY "%SUBLIME%-data" "%APPDATA%\%SUBLIME%\Packages\User" /S
GOTO:EOF

:END
PAUSE
